apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest
        command: ["k6", "run", "/script/load-test.js"]
        volumeMounts:
        - name: script-volume
          mountPath: /script
      restartPolicy: Never
      volumes:
      - name: script-volume
        configMap:
          name: k6-test-script
