apiVersion: v1
kind: Service
metadata:
  name: sketchcabs-loadbalancer
  namespace: ingress-nginx
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "sketchcabs-lb"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: onewaytaxi-loadbalancer
  namespace: ingress-nginx
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "onewaytaxi-lb"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
